package com.yotam.droneedge.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

class AppStrings(
    val code:                String,
    val selectModel:         String,
    val confirm:             String,
    val modelNotFound:       (String) -> String,
    val externalModelDesc:   String,
    val externalModelHint:   String,
    val statusLabel:         String,
    val stateIdle:           String,
    val stateRunning:        String,
    val stateStopping:       String,
    val sourceNoSource:      String,
    val sourceCamera:        String,
    val sourceFile:          String,
    val gallery:             String,
    val start:               String,
    val stop:                String,
    val rec:                 String,
    val saving:              String,
    val dismiss:             String,
    val savedTo:             String,
    val nameRecordingTitle:  String,
    val sessionNameLabel:    String,
    val save:                String,
    val skip:                String,
    val selectSource:        String,
    val sourceCameraBack:    String,
    val sourceVideoFile:     String,
    val sourceDji:           String,
    val sourceFake:          String,
    val galleryTitle:        String,
    val noRecordings:        String,
    val rename:              String,
    val delete:              String,
    val renameSession:       String,
    val deleteSession:       String,
    val deleteConfirmBody:   (String) -> String,
    val cancel:              String,
    val error:               String,
    val ok:                  String,
    val cameraDenied:        String,
    val noUvcCamera:         String,
    val noDjiGoggles:        String,
    val djiDisconnected:     String,
    val usbDisconnected:     String,
) {
    companion object {
        val Hebrew = AppStrings(
            code                = "HE",
            selectModel         = "בחר מודל זיהוי",
            confirm             = "אישור",
            modelNotFound       = { file -> "קובץ המודל '$file' לא נמצא בנכסים." },
            externalModelDesc   = "מודל חיצוני — העתק קבצי .tflite ל-Android/data/com.yotam.droneedge/files/models/ דרך ADB",
            externalModelHint   = "הוסף קבצי .tflite ל-Android/data/com.yotam.droneedge/files/models/ דרך ADB להוספת מודלים",
            statusLabel         = "סטטוס",
            stateIdle           = "לא פעיל",
            stateRunning        = "פועל",
            stateStopping       = "עוצר",
            sourceNoSource      = "ללא מקור",
            sourceCamera        = "מצלמה",
            sourceFile          = "קובץ",
            gallery             = "גלריה",
            start               = "התחל",
            stop                = "עצור",
            rec                 = "הקלט",
            saving              = "שומר…",
            dismiss             = "סגור",
            savedTo             = "נשמר ב-Movies/DroneEdge/",
            nameRecordingTitle  = "שם ההקלטה",
            sessionNameLabel    = "שם הסשן",
            save                = "שמור",
            skip                = "דלג",
            selectSource        = "בחר מקור",
            sourceCameraBack    = "מצלמה (אחורית)",
            sourceVideoFile     = "קובץ וידאו",
            sourceDji           = "משקפי DJI",
            sourceFake          = "מזויף (פיתוח)",
            galleryTitle        = "גלריה",
            noRecordings        = "לא נמצאו הקלטות.",
            rename              = "שנה שם",
            delete              = "מחק",
            renameSession       = "שנה שם סשן",
            deleteSession       = "מחק סשן",
            deleteConfirmBody   = { name -> "למחוק \"$name\"? לא ניתן לבטל פעולה זו." },
            cancel              = "ביטול",
            error               = "שגיאה",
            ok                  = "אישור",
            cameraDenied        = "הרשאת מצלמה נדחתה — אפשר אותה בהגדרות לשימוש במצלמת המכשיר",
            noUvcCamera         = "לא נמצאה מצלמת UVC — חבר מצלמת USB ונסה שוב",
            noDjiGoggles        = "לא זוהו משקפי DJI — חבר דרך USB והדלק את הרחפן",
            djiDisconnected     = "משקפי DJI התנתקו",
            usbDisconnected     = "מצלמת USB התנתקה",
        )

        val English = AppStrings(
            code                = "EN",
            selectModel         = "SELECT DETECTION MODEL",
            confirm             = "CONFIRM",
            modelNotFound       = { file -> "Model file '$file' not found in assets." },
            externalModelDesc   = "External model — push .tflite files to Android/data/com.yotam.droneedge/files/models/ via ADB",
            externalModelHint   = "Drop .tflite files into Android/data/com.yotam.droneedge/files/models/ via ADB to add custom models",
            statusLabel         = "STATUS",
            stateIdle           = "IDLE",
            stateRunning        = "RUNNING",
            stateStopping       = "STOPPING",
            sourceNoSource      = "No Source",
            sourceCamera        = "Camera",
            sourceFile          = "File",
            gallery             = "Gallery",
            start               = "START",
            stop                = "STOP",
            rec                 = "REC",
            saving              = "Saving…",
            dismiss             = "Dismiss",
            savedTo             = "Saved to Movies/DroneEdge/",
            nameRecordingTitle  = "Name this recording",
            sessionNameLabel    = "Session name",
            save                = "Save",
            skip                = "Skip",
            selectSource        = "SELECT SOURCE",
            sourceCameraBack    = "Camera (back)",
            sourceVideoFile     = "Video File",
            sourceDji           = "DJI Goggles",
            sourceFake          = "Fake (dev)",
            galleryTitle        = "GALLERY",
            noRecordings        = "No recordings found.",
            rename              = "Rename",
            delete              = "Delete",
            renameSession       = "Rename session",
            deleteSession       = "Delete session",
            deleteConfirmBody   = { name -> "Delete \"$name\"? This cannot be undone." },
            cancel              = "Cancel",
            error               = "Error",
            ok                  = "OK",
            cameraDenied        = "Camera permission denied — grant it in Settings to use the device camera",
            noUvcCamera         = "No UVC camera found — connect a USB camera and try again",
            noDjiGoggles        = "No DJI Goggles detected — connect via USB and power on the drone",
            djiDisconnected     = "DJI Goggles disconnected",
            usbDisconnected     = "USB camera disconnected",
        )
    }
}

val LocalAppStrings = staticCompositionLocalOf { AppStrings.Hebrew }
